#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Use this one if you just want a count of errors.
#FAIL_COUNT=`rspec --format=progress | grep "example" | grep "fail" | awk {'print $3'}`

# Executes rspec, if there are no errors the string will be null
FAIL_COUNT=`rspec | sed -n '/Failures:/,/Finished in/p'`

if [ -n "$FAIL_COUNT" ]
then
  echo "There are tests broken. Please fix them and commit again."
  echo "$FAIL_COUNT"
  exit 1
else
  echo "All rspec tests are passing."
  exit 0
fi
