# http://www.codeography.com/2013/09/23/how_i_setup_chruby.html
if [[ -f /usr/local/opt/chruby/share/chruby/chruby.sh ]]; then
  source /usr/local/opt/chruby/share/chruby/chruby.sh
  source /usr/local/opt/chruby/share/chruby/auto.sh
else
  echo "Ain't got no chruby"
fi
