# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

source $ZSH/oh-my-zsh.sh

# Save a ton of history
HISTSIZE=20000
HISTFILE=~/.zsh_history
SAVEHIST=20000

# load aliases and variables
source $HOME/.dotfiles/zsh/aliases.sh
source $HOME/.dotfiles/zsh/variables.sh

# load the latest ruby with Chruby
chruby ruby

# # wemux config, a client logs on, then exits
# wemux mirror; exit
